swagger: "2.0"
info:
  description: "Bridge between FaceNet and rest of the world"
  version: "1.0.0"
  title: "FaceNet server"
  contact:
    email: "info@helmes.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/sille"
tags:
  - name: "identify"
    description: "Identification services"
schemes:
  - "http"
paths:
  /find:
    post:
      tags:
        - "identify"
      operationId: "findSimilar"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "image"
          description: "Image of the person"
          schema:
            $ref: "#/definitions/Request"
        - name: "threshold"
          in: "query"
          type: "number"
          required: false
          default: "0.75"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Response"
        500:
          description: "oops!"
  /detect:
    post:
      tags:
        - "identify"
      operationId: "detectFace"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "image"
          description: "Image of the person"
          schema:
            $ref: "#/definitions/Request"
      responses:
        200:
          description: "successful operation"
        404:
          description: "no person found on photo"
        500:
          description: "oops!"
definitions:
  Response:
    type: object
    properties:
      images:
        type: array
        description: Paths to images where person was found
        items:
          type: string
          example: '/mnt/sdcard/image.jpg'
  Request:
    type: object
    properties:
      image:
        type: string
        description: Base64 encoded image
        example: "data:image/png;base64,iVB.."
